name = "boxdbot"
main = "src/worker.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "boxdbot"
database_id = "a00292b5-e893-4103-aa4e-da5db3f30f9c"

[triggers]
crons = ["*/15 * * * *"]

[vars]
DISCORD_APP_ID = ""
DISCORD_PUBLIC_KEY = ""
# DISCORD_BOT_TOKEN is a secret and should be set via `wrangler secret put DISCORD_BOT_TOKEN`

[observability]
[observability.logs]
enabled = true
invocation_logs = true
